name: desktop
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared:
    path: ../shared/
  provider: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - ../assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: ../assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: ../assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: ../assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: ../assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: ../assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: ../assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
